remote_theme: joeeasterly/pages_theme_joeeasterly
sass:
  style: expanded
  # Where you keep your scss files
  sass_dir: _sass

personal-name: Joe Easterly
occupation: Digital Scholarship Librarian
description: Digital Scholarship Librarian, University of Rochester
institution: University of Rochester
title: Joe Easterly
work: https://www.library.rochester.edu/profile/joe_easterly
github: https://github.com/joeeasterly
twitter: https://twitter.com/joeeasterly
youtube: https://www.youtube.com/c/joeeasterly
linkedin: https://www.linkedin.com/in/joeeasterly/
facebook: https://www.facebook.com/joeeasterly
linktree: https://linktr.ee/joeeasterly
cv: https://docs.google.com/document/d/13z3Y7EzGsYt4Z2SPnNt1BIjE40clsWATOcy5yjnWoWE/edit?usp=sharing
calendar: https://outlook.office365.com/owa/calendar/jpe@uofr.onmicrosoft.com/bookings/
orcid: https://orcid.org/0000-0003-2682-6743
isni: https://isni.org/isni/0000000506371694